tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_joint
    joint_max_speed: 1
    joint_speed: .6
    joint_torque_limit: 1
    joint_compliance_slope: 20
    joint_compliance_margin: 2
    joint_compliance_punch:  128
    motor:
        id: 1
        init: 512
        min: 0
        max: 1023

pan_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint
    joint_max_speed: 1
    joint_speed: .6
    joint_torque_limit: 1
    joint_compliance_slope: 20
    joint_compliance_margin: 2
    joint_compliance_punch:  128
    motor:
        id: 2
        init: 512
        min: 0
        max: 1023
